site_name: Grafana-Zabbix Documentation
#site_url: http://docs.grafana.com/
#site_url: /
site_description: Documentation for Grafana-Zabbix, Zabbix monitoring system plugin bundle for Grafana
repo_url: https://github.com/alexanderzobnin/grafana-zabbix/
copyright: Copyright &copy; 2014-2015, Alexander Zobnin

docs_dir: sources
theme: readthedocs


pages:
- Project:
    - 'About Grafana-Zabbix': 'index.md'
- Installation:
    - 'Installation': 'installation/index.md'

# - ['project/cla.md', 'Project', 'Contributor License Agreement']

# - ['installation/index.md', 'Installation', 'Installation']
# - ['installation/troubleshooting.md', 'Installation', 'Troubleshooting']
# - ['installation/migrating_to2.md', 'Installation', 'Migrating from v1.x to v2.x']

# - ['guides/basic_concepts.md', 'User Guides', 'Basic Concepts']
# - ['guides/gettingstarted.md', 'User Guides', 'Getting Started']
# - ['guides/whats-new-in-v2-6.md', 'User Guides', "What's New in Grafana v2.6"]
# - ['guides/whats-new-in-v2-5.md', 'User Guides', "What's New in Grafana v2.5"]
# - ['guides/whats-new-in-v2-1.md', 'User Guides', "What's New in Grafana v2.1"]
# - ['guides/whats-new-in-v2.md', 'User Guides', "What's New in Grafana v2.0"]
# - ['guides/screencasts.md', 'User Guides', 'Screencasts']

# - ['reference/graph.md', 'Reference', 'Graph Panel']
# - ['reference/singlestat.md', 'Reference', 'Singlestat Panel']
# - ['reference/table_panel.md', 'Reference', 'Table Panel']
# - ['reference/dashlist.md', 'Reference', 'Dashboard List Panel']

# - ['tutorials/index.md', 'Tutorials', 'Tutorials']
# - ['tutorials/hubot_howto.md', 'Tutorials', 'How To integrate Hubot and Grafana']
